version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: go-saas-db
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gosaas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go-saas-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_URL=postgresql://admin:password@db:5432/gosaas?sslmode=disable
      - JWT_SECRET=votre-secret-jwt-local # Remplacez par un secret plus robuste si nécessaire
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: go-saas-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - /app/.next
    environment:
      - API_BASE_URL=http://backend:8080
    depends_on:
      - backend

volumes:
  postgres_data: {}
