services:
  - type: web
    name: ivoire-parking # Nom du service unifié
    runtime: go # L'environnement principal est Go, car il lance tout
    buildCommand: |
      # Rendre le script de démarrage exécutable
      chmod +x ./start.sh
      # Build du frontend
      cd frontend && yarn install && yarn build && cd ..
      # Build du backend
      cd backend && go build -o app . && cd ..
    startCommand: ./start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: parking-db
          property: connectionString
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET_KEY
        sync: false

databases:
  - name: parking-db
    databaseName: parking
    user: parking_user
