services:
  - type: web
    name: frontend
    runtime: node
    rootDir: frontend
    buildCommand: yarn && yarn build
    startCommand: yarn start
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        fromService:
          type: web
          name: backend
          property: url
  - type: web
    name: backend
    runtime: go
    rootDir: parking-dashboard/backend
    buildCommand: go build -o app .
    startCommand: ./app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: parking-db
          property: connectionString
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false

databases:
  - name: parking-db
    databaseName: parking
    user: parking_user
